services:
  u2d-internaltool:
    build: .
    container_name: u2d-internaltool
    restart: unless-stopped
    env_file: .env
    volumes:
      - u2d_data:/data
    networks:
      - web

volumes:
  u2d_data:

networks:
  web:
    external: true
