// Response shapes, mirroring the API documentation's Models / Schemas.
// Values are type descriptions; nested objects and arrays nest.

export const SCHEMAS = [
  {
    id: 'webhook-callback',
    name: 'Webhook callback',
    blurb:
      'Every callback is an array of these. `type` says what the item carries and `result` holds the record.',
    shape: {
      queueId: 'string',
      name: 'string',
      url: 'string',
      type: '"Profile" | "Company" | "Activity" | "ActivityPosts" | "ActivityComments" | "ActivityReactions" | "LatestPost" | "PostByUrl" | "partial-profiles" | "partial-companies"',
      status: 'number',
      _id: 'string',
      totalResults: 'number — Sales Navigator queues only, and absent until the first page is scraped',
      result: 'the record named by type',
    },
  },
  {
    id: 'profile',
    name: 'Profile',
    blurb: 'What `result` holds when `type` is "Profile". Also the body of a live /profile response, without `_id`.',
    shape: {
      _id: 'string',
      objectId: 'number',
      linkedinId: 'string',
      url: 'string — LinkedIn slug',
      fullUrl: 'string — https://www.linkedin.com/in/{url}',
      firstName: 'string',
      lastName: 'string',
      headline: 'string',
      location: 'string',
      summary: 'string',
      imageUrl: 'string',
      openToWork: 'boolean',
      isPremium: 'boolean',
      connectionsCount: 'number — only with withFollowersAndConnections',
      followersCount: 'number — only with withFollowersAndConnections',
      skills: ['string — capped at the first 20 without withFullSkillsAndEndorsements'],
      skillsWithEndorsements: [
        { name: 'string', endorsementCount: 'number' },
      ],
      experience: [
        {
          positionId: 'string',
          companyName: 'string',
          title: 'string',
          industry: 'string',
          companyUrl: 'string',
          companyLinkedinId: 'string',
          description: 'string',
          logo: 'string — optional',
          skills: ['string'],
          company: 'string — Company id',
          start: { year: 'number', month: 'number' },
          end: { year: 'number', month: 'number' },
        },
      ],
      education: [
        {
          educationId: 'string',
          schoolName: 'string',
          degreeName: 'string',
          fieldOfStudy: 'string',
          description: 'string',
          logo: 'string — optional',
          start: { year: 'number' },
          end: { year: 'number' },
        },
      ],
      certifications: [
        {
          name: 'string',
          authority: 'string',
          licenseNumber: 'string',
          url: 'string',
          start: { year: 'number', month: 'number' },
          end: { year: 'number', month: 'number' },
        },
      ],
      languages: [{ name: 'string', proficiency: 'string' }],
      publications: [
        {
          name: 'string',
          description: 'string',
          url: 'string',
          publisher: 'string',
          publishedOn: { year: 'number', month: 'number', day: 'number' },
          publicationId: 'string',
          authors: [
            { name: 'string', firstName: 'string', lastName: 'string', publicIdentifier: 'string', headline: 'string' },
          ],
        },
      ],
      patents: [
        {
          title: 'string',
          patentNumber: 'string',
          issuer: 'string',
          issuedOn: { year: 'number', month: 'number', day: 'number' },
          description: 'string',
          patentId: 'string',
          inventors: [
            { name: 'string', firstName: 'string', lastName: 'string', publicIdentifier: 'string', headline: 'string' },
          ],
        },
      ],
      awards: [
        {
          title: 'string',
          issuer: 'string',
          issuedOn: { year: 'number', month: 'number', day: 'number' },
          description: 'string',
          honorId: 'string',
          positionId: 'string',
        },
      ],
      primaryLocale: { country: 'string', language: 'string' },
      birthDateOn: { month: 'number', day: 'number', year: 'number' },
      additionalDataJson: { certificates: ['…'], languages: ['…'], projects: ['…'] },
      interests: { companies: ['…'], groups: ['…'], influencers: ['…'], newsletters: ['…'], schools: ['…'] },
      recommendations: { given: ['…'], received: ['…'] },
      changeLog: [
        { timestamp: 'string', type: 'string', description: 'string', data: 'object — varies by change type' },
      ],
      createdAt: 'string — ISO 8601',
      updatedAt: 'string — ISO 8601',
    },
  },
  {
    id: 'company',
    name: 'Company',
    blurb: 'What `result` holds when `type` is "Company". LinkedIn data, plus Crunchbase data where available.',
    shape: {
      _id: 'string',
      name: 'string',
      linkedinId: 'string',
      linkedinSlug: 'string',
      linkedin: 'string',
      website: 'string',
      logo: 'string',
      industry: 'string',
      location: 'string',
      headquarters: {
        country: 'string', city: 'string', postalCode: 'string',
        line1: 'string', line2: 'string', latitude: 'number', longitude: 'number',
      },
      tagline: 'string',
      description: 'string',
      shortDescription: 'string',
      companyType: 'string',
      numberOfEmployees: 'number',
      employeesRange: { from: 'number', to: 'number' },
      specialities: ['string'],
      hubTags: ['string'],
      activelyHiring: 'boolean',
      phoneNumber: 'string',
      legalName: 'string',
      uuid: 'string',
      rankOrgCompany: 'number',
      foundedOn: { year: 'number', month: 'number', day: 'number' },
      locationIdentifiers: [{ value: 'string', type: 'string' }],
      socialNetworks: [{ socialNetworkType: 'string', url: 'string' }],
      categories: ['string'],
      categoryGroups: ['string'],
      operatingStatus: 'string',
      ipoStatus: 'string',
      fundingStage: 'string',
      fundingTotal: { currency: 'string', amount: 'number' },
      equityFundingTotal: { currency: 'string', amount: 'number' },
      numFundingRounds: 'number',
      numInvestors: 'number',
      numLeadInvestors: 'number',
      lastFundingType: 'string',
      lastEquityFundingType: 'string',
      lastFundingAt: { day: 'number', month: 'number', year: 'number' },
      lastFundingTotal: { currency: 'string', amount: 'number' },
      fundingRounds: [
        {
          announced_on: 'string',
          num_investors: 'number',
          investmentType: 'string',
          money_raised: { currency: 'string', amount: 'number' },
          identifier: { value: 'string', image_id: 'string', permalink: 'string' },
          lead_investor_identifiers: [{ value: 'string', image_id: 'string', permalink: 'string' }],
        },
      ],
      investorIdentifiers: [{ name: 'string' }],
      investorsList: [
        {
          identifier: { value: 'string', permalink: 'string' },
          funding_round_identifier: { value: 'string', image_id: 'string', permalink: 'string' },
          investor_identifier: { value: 'string', image_id: 'string', permalink: 'string' },
        },
      ],
      ipoSummary: {
        ipoSharePrice: { value: 'number', currency: 'string', valueUsd: 'number' },
        stockLink: { label: 'string', value: 'string' },
        wentPublicOn: 'string',
      },
      acquirerIdentifier: { name: 'string' },
      acquisitionAnnouncedOn: { day: 'number', month: 'number', year: 'number' },
      acquisitionPrice: { currency: 'string', amount: 'number' },
      acquisitionType: 'string',
      acquisitions: [
        {
          acquiree_identifier: { value: 'string', image_id: 'string', permalink: 'string', role: 'string' },
          announced_on: { value: 'string', precision: 'string' },
          identifier: { value: 'string', image_id: 'string', permalink: 'string' },
          price: { currency: 'string', amount: 'number' },
        },
      ],
      lastKeyEmployeeChangeDate: { day: 'number', month: 'number', year: 'number' },
      lastLayoffDate: { day: 'number', month: 'number', year: 'number' },
      signalsLayoffs: [
        {
          identifier: { value: 'string' },
          activity_entities: [{ value: 'string', image_id: 'string', permalink: 'string' }],
          activity_properties: { url: 'string', title: 'string', author: 'string', publisher: 'string' },
          activity_date: 'string',
        },
      ],
      createdAt: 'string — ISO 8601',
      updatedAt: 'string — ISO 8601',
    },
  },
  {
    id: 'partial-profile',
    name: 'Partial profile',
    blurb:
      'The lighter lead record from partial-sales-profiles. Only linkedinId, currentPositions, badges and scrapedAt are always present; webhook callbacks omit _id, createdAt and updatedAt.',
    shape: {
      _id: 'string',
      linkedinId: 'string',
      objectId: 'number',
      firstName: 'string',
      lastName: 'string',
      fullName: 'string',
      geoRegion: 'string',
      summary: 'string',
      imageUrl: 'string',
      premium: 'boolean',
      openLink: 'boolean',
      memorialized: 'boolean',
      blockThirdPartyDataSharing: 'boolean',
      currentPositions: [
        {
          title: 'string',
          companyName: 'string',
          description: 'string',
          companyLinkedinId: 'number',
          companyIndustry: 'string',
          companyLocation: 'string',
          companyLogo: 'string',
          startedOn: { month: 'number', year: 'number' },
        },
      ],
      badges: [{ id: 'string', displayValue: 'string' }],
      scrapedAt: 'string — ISO 8601',
      createdAt: 'string — ISO 8601',
      updatedAt: 'string — ISO 8601',
    },
  },
  {
    id: 'partial-company',
    name: 'Partial company',
    blurb:
      'The lighter account record from partial-sales-companies. Note linkedinId is a number here and a string on the full Company.',
    shape: {
      _id: 'string',
      linkedinId: 'number',
      companyName: 'string',
      description: 'string',
      industry: 'string',
      employeeCountRange: 'string',
      employeeDisplayCount: 'string',
      logo: 'string',
      badges: [{ id: 'string', displayValue: 'string' }],
      scrapedAt: 'string — ISO 8601',
      createdAt: 'string — ISO 8601',
      updatedAt: 'string — ISO 8601',
    },
  },
  {
    id: 'activity',
    name: 'Activity',
    blurb:
      'One document per profile. A repost is not its own list — it is a post with isRepost set and the original in repostedPost.',
    shape: {
      _id: 'string',
      profile: 'Profile — the full enriched profile',
      linkedinObjectId: 'number',
      profileUrn: 'string',
      slug: 'string — LinkedIn slug',
      profileUrl: 'string',
      scrapedAt: 'string — ISO 8601',
      partial: { posts: 'boolean', comments: 'boolean', reactions: 'boolean' },
      posts: [
        {
          url: 'string',
          urn: 'string',
          shareUrn: 'string — nullable',
          author: { name: 'string', url: 'string', headline: 'string — nullable', avatarUrl: 'string — nullable' },
          text: 'string',
          postedAt: 'string — as LinkedIn reports it, not ISO',
          reactionsCount: 'number',
          commentsCount: 'number',
          repostsCount: 'number',
          reactionsByType: [{ type: 'string', count: 'number' }],
          contentType: 'string — "unknown" when undetermined',
          media: [
            {
              type: '"image" | "video" | "document"',
              url: 'string',
              thumbnailUrl: 'string — nullable',
              title: 'string — nullable',
              durationMs: 'number — nullable',
            },
          ],
          article: { title: 'string', subtitle: 'string — nullable', url: 'string', thumbnailUrl: 'string — nullable' },
          isRepost: 'boolean',
          repostedPost: 'TargetPost — nullable',
          isEdited: 'boolean',
          mentions: [
            { name: 'string', publicIdentifier: 'string — nullable', url: 'string — nullable', urn: 'string — nullable' },
          ],
          companyMentions: ['same shape as mentions'],
          hashtags: ['string'],
        },
      ],
      comments: [
        {
          urn: 'string',
          url: 'string',
          text: 'string',
          postedAt: 'string — as LinkedIn reports it',
          repliesCount: 'number',
          targetPost: 'TargetPost',
        },
      ],
      reactions: [
        { reactionType: 'string', reactedAt: 'string — as LinkedIn reports it', targetPost: 'TargetPost' },
      ],
      createdAt: 'string — ISO 8601',
      updatedAt: 'string — ISO 8601',
    },
  },
  {
    id: 'target-post',
    name: 'TargetPost',
    blurb: 'The post a comment, reaction or repost points at.',
    shape: {
      url: 'string',
      urn: 'string',
      textSnippet: 'string',
      author: { name: 'string', url: 'string', headline: 'string — nullable' },
      reactionsCount: 'number',
      commentsCount: 'number',
      repostsCount: 'number',
    },
  },
  {
    id: 'latest-post',
    name: 'Latest post',
    blurb:
      'One document per profile holding its most recent item. In a webhook callback the post fields sit under result.post rather than on the record.',
    shape: {
      _id: 'string',
      profile: 'Profile — the full enriched profile',
      linkedinObjectId: 'number',
      slug: 'string — LinkedIn slug',
      profileUrl: 'string',
      content: 'string — the commentary, empty when not the person’s own writing',
      date: 'string — ISO 8601 when derivable, else the relative text LinkedIn shows',
      type: '"post" | "repost" | "reaction" | "comment"',
      isOwnContent: 'boolean',
      originalAuthor: 'string — empty unless type is "repost"',
      originalContent: 'string — empty unless type is "repost"',
      scrapedAt: 'string — ISO 8601',
      createdAt: 'string — ISO 8601',
      updatedAt: 'string — ISO 8601',
    },
  },
  {
    id: 'post-by-url',
    name: 'Post by URL',
    blurb:
      'One document per post, keyed by its URN. No profile field — the author is embedded in post.author, since the post need not belong to a profile you have enriched.',
    shape: {
      _id: 'string',
      urn: 'string — urn:li:activity:<id>, urn:li:share:<id> or urn:li:ugcPost:<id>',
      shareUrn: 'string — nullable',
      postUrl: 'string — the canonical url LinkedIn reports',
      requestedUrl: 'string — the url you sent, query string and trailing slash stripped',
      post: 'the same shape as an entry in the Activity posts array',
      scrapedAt: 'string — ISO 8601',
      createdAt: 'string — ISO 8601',
      updatedAt: 'string — ISO 8601',
    },
  },
]
